DoTheZ-Team/glue-fe

src/app/(auth)/auth/api/index.ts
src/app/(auth)/auth/api/queries.tsx
src/app/(auth)/auth/page.tsx
src/app/(auth)/login/layout.tsx
src/app/(auth)/login/page.tsx
src/app/lib/getQueryClient.tsx
src/components/Common/Icons/KakaoLoginIcon.tsx
src/components/Common/Icons/index.tsx
src/middleware.ts

- #26 을 구현했습니다.
<br>
<br>
<br>
<br>
- 추후 로그인 로직이 변경되거나 `middleware`의 private 페이지가 추가될 예정입니다.
- close #26 
<br>

GLUE-300-kakao-로그인-구현

---

src/app/blog/[blogId]/post/[postId]/components/Comments/api/index.ts
src/app/blog/[blogId]/post/[postId]/components/Comments/api/quries.ts
src/app/blog/[blogId]/post/[postId]/components/Comments/hooks/index.ts
src/app/blog/[blogId]/post/[postId]/components/Comments/index.tsx
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/api/index.tsx
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/api/quries.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/hooks/index.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
src/app/blog/[blogId]/post/[postId]/layout.tsx
src/app/blog/[blogId]/post/[postId]/page.tsx
src/components/Common/Toast/index.tsx

- #33 을 구현했습니다.
<br>
<br>
https://github.com/DoTheZ-Team/glue-fe/assets/86355699/de26b128-4259-463f-85f2-4bab14d30eda
<br>
<br>
close #33 
<br>

GLUE-316-좋아요-api-구현

---

src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/api/index.tsx
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/api/quries.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
src/app/blog/[blogId]/post/[postId]/layout.tsx

- #47 를 구현했습니다.
<br>
<br>
<br>
<br>
close #47 
<br>

GLUE-335-글-삭제-api-연결

---

.github/workflows/glue-client.yml
Dockerfile
next.config.mjs

- #54 를 구현합니다.
<br>
<br>
<br>
<br>
close #54 
<br>

GLUE-363-CICD-파이프라인-구축

---

src/app/(publish)/components/PostEditor/index.tsx
src/app/(publish)/store/index.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/hooks/index.ts
src/app/blog/[blogId]/post/[postId]/components/StickerRenderer/index.tsx
src/app/blog/[blogId]/post/[postId]/page.tsx

- #52 를 구현했습니다.
<br>
<br>
<br>
<br>
close #52 
<br>

GLUE-360-글작성-스티커-api-구현

---

src/api/core.ts
src/middleware.ts

- #60 을 구현했습니다.
<br>
<br>
<br>
<br>
close #60 
<br>

GLUE-369-private-경로-제한

---

.github/workflows/client-server.yaml
.github/workflows/glue-client.yml
Dockerfile

Dockerfile과 client-server.yaml 파일 추가하였습니다.
<br>
1. Dockerfile에서 아래와 같은 부분으로 pnpm 설치 후 같은 환경에서 사용하도록 하였습니다.
```
FROM deps AS builder
```
2. github-actions.yaml (client-server.yaml) 파일 수정
Repository Checkout을 하지 않아, .env 파일 작성이 안되는 문제를 해결하였습니다.
<br>
<br>
Glue-Client 현재 IP 주소
```
61.109.238.188
```
<br>
추후 도메인 적용 예졍
TODO
<br>

Glue-364-CI/CD 구축

---

src/app/(auth)/auth/page.tsx
src/components/Common/NavigationIcons/index.tsx

- 빌드 트리거를 위한 코드를 변경했습니다.
- 현재 notting to change 를 통해 github actions가 실패했기 때문입니다.
<br>
<br>
<br>
<br>
<br>

GLUE-376-불필요한-코드-삭제

---

src/app/(auth)/auth/api/queries.ts
src/app/(publish)/api/index.ts
src/app/(publish)/api/queries.tsx
src/components/MouseImageGallery/index.tsx

- 매칭 버튼을 추가했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-377-매칭-버튼-추가

---

next.config.mjs

- 이미지 렌더링을 위한 `next.config` 설정을 변경했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-380-image의-remotePatterns-추가

---

src/api/api.ts
src/api/index.ts
src/components/Common/Editor/hooks/index.tsx
src/components/Common/FileEdit/index.tsx

- #72 를 구현했습니다.
<br>
<br>
<br>
<br>
close #72 
<br>

GLUE 378 이미지 첨부 api 연결

---

next.config.mjs

- `next.config`의 오타를 수정했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-386 오타 수정

---

next.config.mjs

- next.config를 수정했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-378 이미지 주소 수정

---

next.config.mjs

- next.config를 수정했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-386 next.config 수정

---

next.config.mjs
src/app/(publish)/components/PostEditor/index.tsx
src/app/(publish)/components/StickerPannel/components/StickerPannelRenderer/index.tsx
src/components/Common/Dropdown/index.tsx

- 이미지 로딩 오류를 해결했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-387 이미지 로딩을 위해 Image 태그의 loader 추가

---

src/app/blog/[blogId]/post/[postId]/components/StickerRenderer/index.tsx

- `Image` 태그에 `loader`를 추가했습니다.
<br>
<br>
<br>
<br>
<br>

fix: nextjs Image 태그에 loader 추가

---

src/api/core.ts
src/app/(publish)/components/PostEditor/index.tsx
src/app/blog/[blogId]/components/Albums/Slider.tsx
src/app/blog/[blogId]/components/BlogBackground/index.tsx
src/app/blog/[blogId]/components/Board/BoardContent.tsx
src/app/blog/[blogId]/components/ProfileBox/index.tsx
src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/Comments/ChildComments/ChildComments.tsx
src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/Comments/Comment.tsx
src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/index.tsx
src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
src/app/blog/[blogId]/post/[postId]/page.tsx
src/app/match/page.tsx
src/app/mypage/components/Common/FileThumbnails.tsx
src/app/search/components/BlogList/BlogCard.tsx
src/app/subscribe/components/FeedBox/index.tsx
src/components/Common/Icons/Mypage.tsx
src/components/Common/Icons/index.tsx
src/components/MouseImageGallery/index.tsx

- QA에서 발견된 문제를 수정했습니다.
<br>
<br>
<br>
<br>
<br>

Glue 381 qa 수정

---

src/app/(publish)/hooks/useWritePost.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/hooks/index.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
src/utils/common/Clipboard.ts
src/utils/common/Device.ts
src/utils/common/index.ts

- 복사 기능을 구현했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE 381 복사 기능 구현

---

src/app/blog/[blogId]/components/Albums/Slider.tsx
src/app/blog/[blogId]/page.tsx

<br> 글쓰기 라우팅 추가하였습니다.
<br>
<br>
<br> 내 블로그일 경우 글쓰기 아이콘 추가
<br>

feat: 내 블로그일 경우 글쓰기 아이콘 추가

---

src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx

- 글 상세 페이지에서 프로필 사용자 이미지 API를 연결했습니다.
<br>
<br>
<br>
<br>
<br>

GLUE-383 프로필 사용자 이미지 API 연결

---

src/app/(auth)/auth/api/queries.ts

<br> 로그인시 loginId가 업데이트되지 않는 이슈 발견
<br>
<br>
<br>
<br>

fix: loginId전역관리 오류 수정

---

src/app/(auth)/auth/api/queries.ts
src/components/Common/UserContext/UserProviderWrapper.tsx

<br> loginId가 업데이트 안되는 이슈 발견
<br>
<br>
<br>
<br>

Glue-303-login-id-오류수정

---

src/app/blog/[blogId]/components/Board/BoardContent.tsx
src/app/blog/[blogId]/components/Board/index.tsx
src/components/MouseImageGallery/index.tsx

<br>페이지네이션 오류 해결 및 랜딩에서 라우팅 경로 변경
<br>
<br>
<br>
<br>

GLUE-333-이슈-해결

---

src/app/blog/[blogId]/components/Board/BoardContent.tsx
src/app/blog/[blogId]/components/Board/index.tsx
src/app/subscribe/components/Feed/FeedContent.tsx
src/app/subscribe/components/FeedBox/index.tsx
src/app/subscribe/components/ProfileCard/index.tsx
src/app/subscribe/components/Subscription/FollowListContent.tsx
src/app/subscribe/components/Subscription/FollowerListContent.tsx
src/components/MouseImageGallery/index.tsx

<br> 구독페이지 라우팅 추가
<br>
<br>
<br>
<br>

Glue 333 이슈 해결
